import React, { useState } from 'react';
import { Mail, Globe, Github, Download, ArrowLeft, Loader2, Award, Code, Briefcase } from 'lucide-react';
import { getResumeData } from '../utils/personaLogic';
import html2pdf from 'html2pdf.js';

const ResumeBuilder = ({ data, onBack }) => {
  const [isDownloading, setIsDownloading] = useState(false);
  const resume = getResumeData(data);

  // DOWNLOAD LOGIC
const downloadResume = async () => {
    setIsDownloading(true);
    const element = document.getElementById('resume-sheet');
    
    // Configuration for a sharp, professional A4 look
    const opt = {
      margin: 0,
      filename: `${data.user}_Professional_CV.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { 
        scale: 3, // Higher scale for professional print quality
        useCORS: true, // Critical for GitHub avatars
        letterRendering: true,
        scrollX: 0,
        scrollY: 0
      },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    try {
      // Use the promise-based API to ensure capture completes
      await html2pdf().set(opt).from(element).save();
    } catch (err) {
      console.error("PDF Generation Error:", err);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-100 p-4 md:p-12 font-sans">
      {/* Action Bar */}
      <div className="max-w-4xl mx-auto mb-8 flex justify-between items-center bg-white/50 backdrop-blur-md p-4 rounded-2xl border border-white">
        <button onClick={onBack} className="flex items-center gap-2 text-slate-600 font-bold hover:text-indigo-600 transition-all text-sm group">
          <ArrowLeft size={18} className="group-hover:-translate-x-1 transition-transform" /> 
          RETURN TO DASHBOARD
        </button>
        
        <button 
          onClick={downloadResume}
          disabled={isDownloading}
          className="bg-indigo-600 text-white px-8 py-3 rounded-xl font-bold flex items-center gap-2 hover:bg-indigo-700 transition-all shadow-xl shadow-indigo-200 disabled:opacity-50"
        >
          {isDownloading ? <Loader2 size={18} className="animate-spin" /> : <Download size={18} />}
          {isDownloading ? "PREPARING PDF..." : "DOWNLOAD PDF CV"}
        </button>
      </div>

      {/* THE RESUME SHEET (Standard A4 Proportion) */}
      <div 
        id="resume-sheet" 
        className="bg-white shadow-2xl mx-auto rounded-sm overflow-hidden flex flex-col md:flex-row min-h-[1050px] w-full max-w-[850px]"
      >
        {/* Sidebar (25% Width) */}
        <aside className="w-full md:w-64 bg-slate-900 text-slate-300 p-8 flex flex-col border-r border-slate-800">
          <div className="mb-10 text-center md:text-left">
             <div className="w-24 h-24 bg-indigo-600 rounded-2xl mx-auto md:mx-0 flex items-center justify-center mb-4 shadow-lg shadow-indigo-500/20">
                <span className="text-4xl font-black text-white">{data.user.charAt(0).toUpperCase()}</span>
             </div>
             <h2 className="text-xl font-black text-white tracking-tight">{data.user}</h2>
             <p className="text-xs font-bold text-indigo-400 uppercase tracking-widest mt-1">Impact Score: {data.points}</p>
          </div>

          <div className="space-y-8">
            <section>
              <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-[0.2em] mb-4 flex items-center gap-2">
                <Globe size={12} /> Digital Presence
              </h3>
              <div className="text-xs space-y-3 font-medium">
                <p className="hover:text-white transition-colors cursor-pointer">github.com/{data.user}</p>
                <p className="text-slate-500 italic">Verified Developer Profile</p>
              </div>
            </section>

            <section>
              <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-[0.2em] mb-4 flex items-center gap-2">
                <Code size={12} /> Tech Stack
              </h3>
              <div className="flex flex-wrap gap-2">
                {resume.coreCompetencies.map((skill, i) => (
                  <span key={i} className="bg-slate-800 text-slate-200 px-2 py-1 rounded text-[10px] font-bold border border-slate-700">
                    {skill}
                  </span>
                ))}
              </div>
            </section>
          </div>

          <div className="mt-auto pt-10">
             <div className="p-4 bg-indigo-900/30 border border-indigo-500/20 rounded-xl">
                <p className="text-[9px] font-bold text-indigo-300 leading-relaxed uppercase tracking-tighter">
                  Quantified GitHub Impact Analysis Generated by SkillSpectra AI Engine.
                </p>
             </div>
          </div>
        </aside>

        {/* Main Content (75% Width) */}
        <main className="flex-1 p-10 md:p-14">
          {/* Header */}
          <header className="mb-12">
            <h1 className="text-5xl font-black text-slate-900 tracking-tighter mb-2 italic">RESUME.</h1>
            <div className="h-1.5 w-20 bg-indigo-600 rounded-full mb-6"></div>
            <p className="text-slate-500 font-medium leading-relaxed max-w-lg">
              {resume.summary}
            </p>
          </header>

          {/* Section: Projects */}
          <section className="mb-12">
            <div className="flex items-center gap-3 mb-8">
              <div className="p-2 bg-slate-100 rounded-lg"><Briefcase size={20} className="text-slate-900" /></div>
              <h3 className="text-sm font-black text-slate-900 uppercase tracking-[0.3em]">Key Technical Projects</h3>
            </div>

            <div className="space-y-8">
              {resume.topProjects.map((project, i) => (
                <div key={i} className="relative pl-6 border-l-2 border-slate-100 group">
                  <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-white border-2 border-slate-200 group-hover:border-indigo-600 transition-colors" />
                  <div className="flex justify-between items-baseline mb-1">
                    <h4 className="text-lg font-black text-slate-800 group-hover:text-indigo-600 transition-colors">{project.name}</h4>
                    <span className="text-[11px] font-bold text-slate-400 tracking-widest">{project.metrics}</span>
                  </div>
                  <p className="text-slate-500 text-sm leading-relaxed mb-3">{project.description}</p>
                  <div className="flex items-center gap-2">
                     <span className="text-[10px] font-black text-indigo-600 uppercase bg-indigo-50 px-2 py-0.5 rounded">
                        Build with {project.tech || 'Modern Web Tech'}
                     </span>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Section: Metrics */}
          <section>
            <div className="flex items-center gap-3 mb-8">
              <div className="p-2 bg-slate-100 rounded-lg"><Award size={20} className="text-slate-900" /></div>
              <h3 className="text-sm font-black text-slate-900 uppercase tracking-[0.3em]">GitHub Statistics</h3>
            </div>
            <div className="grid grid-cols-3 gap-6">
              <div className="bg-slate-50 p-4 rounded-2xl border border-slate-100">
                <p className="text-[10px] font-bold text-slate-400 uppercase mb-1">Repositories</p>
                <p className="text-2xl font-black text-slate-900">{data.repo_count}</p>
              </div>
              <div className="bg-slate-50 p-4 rounded-2xl border border-slate-100">
                <p className="text-[10px] font-bold text-slate-400 uppercase mb-1">Followers</p>
                <p className="text-2xl font-black text-slate-900">{data.followers}</p>
              </div>
              <div className="bg-slate-50 p-4 rounded-2xl border border-slate-100">
                <p className="text-[10px] font-bold text-slate-400 uppercase mb-1">Top Tech</p>
                <p className="text-2xl font-black text-slate-900">{data.top_lang}</p>
              </div>
            </div>
          </section>
        </main>
      </div>
    </div>
  );
};

export default ResumeBuilder;